pipeline:
  name: simple-website-build
  identifier: simple_website_build
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build and Push
        identifier: build_and_push
        type: CI
        spec:
          cloneCodebase: false
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: harnessk8sconnector
              namespace: default
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  name: Clone Repository
                  identifier: clone_repo
                  type: Run
                  spec:
                    connectorRef: harnessk8sconnector
                    image: alpine/git:latest
                    shell: Sh
                    command: |
                      # Clone the repository
                      git clone https://github.com/devsecops808/harnesscd-example-apps.git
                      cd harnesscd-example-apps
                      # If you need a specific branch
                      git checkout master
                      ls -la
              - step:
                  name: Build and Push Image
                  identifier: build_and_push_image
                  type: BuildAndPushDockerRegistry
                  spec:
                    connectorRef: devopsone808dockerrepo
                    repo: devopsone808/simple-website
                    tags:
                      - <+pipeline.sequenceId>
                      - latest
                    dockerfile: harnesscd-example-apps/simple-website/Dockerfile
                    context: harnesscd-example-apps/simple-website
                    buildArgs:
                      VERSION: <+pipeline.sequenceId>
          caching:
            enabled: true
            paths:
              - /root/.m2
              - /root/.gradle
          buildIntelligence:
            enabled: true
        description: ""
    - stage:
        name: Deploy
        identifier: Deploy
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: simple-website-deployment
          project: default_project
          inputs: {}
  variables:
    - name: buildTag
      type: String
      description: Docker image tag to be built
      value: <+pipeline.sequenceId>
  trigger:
    name: simple-website-build-trigger
    identifier: simple_website_build_trigger
    enabled: true
    type: Webhook
    spec:
      type: Github
      spec:
        connectorRef: harnessgitconnector
        repoName: harnesscd-example-apps
        branchName: master
        events:
          - type: Push
        paths:
          - includes:
              - simple-website/**
