pipeline:
  name: simple-website-deployment
  identifier: simple_website_deployment
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Website
        identifier: deploy_website
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: simple-website
          environment:
            environmentRef: harnessdevenvdep
            deployToAll: false
            infrastructureDefinitions:
              - identifier: harnessk8sinfradep
          execution:
            steps:
              - step:
                  name: Rolling Deployment
                  identifier: rollingDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Rolling Rollback
                  identifier: rollingRollback
                  type: K8sRollingRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback 
  variables:
    - name: imageTag
      type: String
      description: "Docker image tag to be deployed"
      value: latest
  artifacts:
    primary:
      type: DockerRegistry
      spec:
        connectorRef: devopsone808dockerrepo
        imagePath: docker.io/devopsone808/simple-website