service:
    name: simple-website
    identifier: simple-website
    orgIdentifier: default
    projectIdentifier: default_project
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: simple-website-manifests
                    type: Kustomize
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            basePath: simple-website
                            folderPath: simple-website/k8s
                            repoName: harnesscd-example-apps
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
            artifacts:
                primary:
                    type: DockerRegistry
                    spec:
                        connectorRef: harnessdockerconnector
                        imagePath: devopsone808/simple-website
                        tag: 1.0.0
    gitOpsEnabled: false 