service:
    name: simple-website
    identifier: simple_website
    orgIdentifier: default
    projectIdentifier: default_project
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: simple_website_manifests
                    type: Kustomize
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            basePath: simple-website
                            folderPath: simple-website/k8s
                            repoName: harnesscd-example-apps
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
            artifacts:
                primary:
                    type: DockerRegistry
                    spec:
                        connectorRef: devopsone808dockerrepo
                        imagePath: docker.io/devopsone808/simple-website
                        tag: latest
    gitOpsEnabled: false