service:
    name: harness_sockshop
    identifier: harnesssockshop
    orgIdentifier: default
    projectIdentifier: default_project
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: sockshop
                    type: Kustomize
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            basePath: sock-shop
                            folderPath: sock-shop
                            repoName: harnesscd-example-apps
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false 