service:
    name: harness_sockshop
    identifier: harnesssockshop
    serviceDefinition:
        type: Kubernetes
        spec:
            manifests:
                - manifest:
                    identifier: sockshop
                    type: K8sManifest
                    spec:
                      store:
                        type: Github
                        spec:
                            connectorRef: harnessgitconnector
                            gitFetchType: Branch
                            paths:
                                - sock-shop/kustomization.yaml
                                - sock-shop/base/
                            repoName: harnesscd-example-apps
                            branch: master
                        skipResourceVersioning: false
                        enableDeclarativeRollback: false
    gitOpsEnabled: false 