apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-website
  namespace: simple-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-website
  template:
    metadata:
      labels:
        app: simple-website
    spec:
      containers:
      - name: simple-website
        image: devopsone808/simple-website:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: docker-registry-credentials