apiVersion: v1
kind: Service
metadata:
  name: simple-website-sa
  namespace: simple-website
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: simple-website